### ISSUE TITLE
es 1.6下报错

### ISSUE THREAD

**Issue by zhangwenzhao** [lindstromhenrik/elasticsearch-analysis-file-watcher-synonym#3]
是不是对1.6+版本支持有问题 插件问题？

**Comment by zhangwenzhao** [comment]
[2015-12-18 22:33:16,232][DEBUG][action.search.type       ] [SJB-1] All shards failed for phase: [query]
org.elasticsearch.indices.IndexMissingException: [xxxxxxx] missing
        at org.elasticsearch.indices.IndicesService.indexServiceSafe(IndicesService.java:288)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:547)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:532)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:294)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
